# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoPesquisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=60)),
                ('sigla', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=110)),
                ('preco', models.FloatField()),
                ('situacao', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoPesquisa.Categorias')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=60)),
                ('login', models.TextField(max_length=40)),
                ('senha', models.TextField(max_length=32)),
                ('datainc', models.DateField(default=datetime.datetime(2017, 1, 24, 13, 27, 17, 609603, tzinfo=utc))),
                ('dataalt', models.DateField(default=datetime.datetime(2017, 1, 24, 13, 27, 17, 609603, tzinfo=utc))),
            ],
        ),
    ]
