# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoPesquisa', '0002_categorias_produtos_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='sigla',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nome',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='user',
            name='dataalt',
            field=models.DateField(default=datetime.datetime(2017, 1, 24, 17, 39, 26, 834053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='datainc',
            field=models.DateField(default=datetime.datetime(2017, 1, 24, 17, 39, 26, 834053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='senha',
            field=models.CharField(max_length=32),
        ),
    ]
